# Generated by Django 2.2.16 on 2022-01-24 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ветеринарного учреждения')),
                ('slug', models.SlugField(help_text='Здесь будет уникальный адрес страницы. Можно использовать буквы, числа, символы подчеркивания и дефисы', unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Ветеринарное учреждение',
                'verbose_name_plural': 'Ветеринарные учреждения',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата комментария', verbose_name='Дата')),
                ('author', models.ForeignKey(help_text='Автор комментария.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('clinic', models.ForeignKey(help_text='Ветеринарное учреждение, к которому будет относиться комментарий.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='places.Clinic', verbose_name='Ветеринарное учреждение')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created',),
            },
        ),
    ]
