# Generated by Django 2.2.16 on 2022-01-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_clinic_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ('title',), 'verbose_name': 'Ветеринарное учреждение', 'verbose_name_plural': 'Ветеринарные учреждения'},
        ),
    ]
